name: dart_intro_2
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/RamaBataineh/dartintro55.git

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
 emojis: ^0.9.9
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
